[package]
name = "streamling-plugin-derive"
version = "0.1.0"
edition = "2024"
rust-version = "1.90.0"
description = "Derive macros for the Streamling plugin SDK."
license-file.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[lints.clippy]
too_many_arguments = "allow"

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
